[package]
name = "mano"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anstyle = "1.0.5"
clap = { version = "4.5.1", features = ["derive"] }
notify = "6.1.1"
